// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Account
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string ImageUrl { get; set; }

    public string Role { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<DeviceToken> DeviceTokens { get; set; } = new List<DeviceToken>();

    public virtual ICollection<FacilityStaff> FacilityStaffs { get; set; } = new List<FacilityStaff>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual ICollection<NotificationHistory> NotificationHistories { get; set; } = new List<NotificationHistory>();

    public virtual ICollection<UserMembership> UserMemberships { get; set; } = new List<UserMembership>();
}