// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class AppointmentSurvey
{
    public int SurveyId { get; set; }

    public int AppointmentId { get; set; }

    public int QuestionId { get; set; }

    public int? AnswerId { get; set; }

    public string AnswerText { get; set; }

    public decimal? TemperatureC { get; set; }

    public int? HeartRateBpm { get; set; }

    public int? SystolicBpmmHg { get; set; }

    public int? DiastolicBpmmHg { get; set; }

    public int? OxygenSatPercent { get; set; }

    public string DecisionNote { get; set; }

    public bool? ConsentObtained { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual SurveyAnswer Answer { get; set; }

    public virtual VaccinationAppointment Appointment { get; set; }

    public virtual SurveyQuestion Question { get; set; }
}