// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class AppointmentSchedule
{
    public int ScheduleId { get; set; }

    public int FacilityId { get; set; }

    public int SlotId { get; set; }

    public DateOnly Date { get; set; }

    public int? BookedCount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual VaccinationFacility Facility { get; set; }

    public virtual ScheduleSlot Slot { get; set; }

    public virtual ICollection<VaccinationAppointment> VaccinationAppointments { get; set; } = new List<VaccinationAppointment>();
}