// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class ChildDiary
{
    public int DiaryId { get; set; }

    public int ChildId { get; set; }

    public DateOnly RecordDate { get; set; }

    public int MilkAmount { get; set; }

    public int FeedingTimes { get; set; }

    public int DiaperChanges { get; set; }

    public decimal SleepHours { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}