// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Child
{
    public int ChildId { get; set; }

    public int MemberId { get; set; }

    public int? NationId { get; set; }

    public string FullName { get; set; }

    public DateTime BirthDate { get; set; }

    public string Gender { get; set; }

    public string BloodType { get; set; }

    public string AllergiesNotes { get; set; }

    public string MedicalHistory { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<ChildVaccineProfile> ChildVaccineProfiles { get; set; } = new List<ChildVaccineProfile>();

    public virtual ICollection<DailyRecord> DailyRecords { get; set; } = new List<DailyRecord>();

    public virtual ICollection<GrowthRecord> GrowthRecords { get; set; } = new List<GrowthRecord>();

    public virtual Member Member { get; set; }

    public virtual Nationality Nation { get; set; }

    public virtual ICollection<VaccinationAppointment> VaccinationAppointments { get; set; } = new List<VaccinationAppointment>();
}