// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class ChildVaccination
{
    public int VaccinationId { get; set; }

    public int ChildId { get; set; }

    public int VaccineId { get; set; }

    public int FacilityId { get; set; }

    public DateTime VaccinationDate { get; set; }

    public int DoseNumber { get; set; }

    public DateTime? NextVaccinationDate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }
}