// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Child
{
    public int ChildId { get; set; }

    public int UserId { get; set; }

    public string FullName { get; set; }

    public string ParentName { get; set; }

    public string ParentNumber { get; set; }

    public DateTime BirthDate { get; set; }

    public string Gender { get; set; }

    public string BloodType { get; set; }

    public string AllergiesNotes { get; set; }

    public bool Status { get; set; }

    public string MedicalHistory { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}