// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class ChildVaccineProfile
{
    public int VaccineProfileId { get; set; }

    public int ChildId { get; set; }

    public int DiseaseId { get; set; }

    public int AppointmentId { get; set; }

    public int VaccineId { get; set; }

    public int DoseNum { get; set; }

    public DateOnly ExpectedDate { get; set; }

    public DateOnly ActualDate { get; set; }

    public string Status { get; set; }

    public bool IsRequired { get; set; }

    public string Priority { get; set; }

    public long CreatedAt { get; set; }

    public long UpdatedAt { get; set; }

    public virtual VaccinationAppointment Appointment { get; set; }

    public virtual Child Child { get; set; }

    public virtual Disease Disease { get; set; }

    public virtual Vaccine Vaccine { get; set; }
}