// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class DeviceToken
{
    public int DeviceTokenId { get; set; }

    public int AccountId { get; set; }

    public string Token { get; set; }

    public string DeviceType { get; set; }

    public string DeviceInfo { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime LastUsedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<NotificationDeliveryStatus> NotificationDeliveryStatuses { get; set; } = new List<NotificationDeliveryStatus>();
}