// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Disease
{
    public int DiseaseId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Symptoms { get; set; }

    public string Treatment { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ChildVaccineProfile> ChildVaccineProfiles { get; set; } = new List<ChildVaccineProfile>();

    public virtual ICollection<VaccineDisease> VaccineDiseases { get; set; } = new List<VaccineDisease>();

    public virtual ICollection<VaccineTemplate> VaccineTemplates { get; set; } = new List<VaccineTemplate>();
}