// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class DoctorProfile
{
    public int DoctorId { get; set; }

    public int Age { get; set; }

    public string Specialization { get; set; }

    public string Certifications { get; set; }

    public string University { get; set; }

    public string Bio { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual FacilityStaff Doctor { get; set; }
}