// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class FacilityRating
{
    public int RatingId { get; set; }

    public int FacilityId { get; set; }

    public int MemberId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public int ServiceQuality { get; set; }

    public int FacilityCleanliness { get; set; }

    public int StaffAttitude { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual VaccinationFacility Facility { get; set; }

    public virtual Member Member { get; set; }
}