// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class FacilityStaff
{
    public int StaffId { get; set; }

    public int AccountId { get; set; }

    public int FacilityId { get; set; }

    public string FullName { get; set; }

    public int? Phone { get; set; }

    public string Email { get; set; }

    public string Position { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual DoctorProfile DoctorProfile { get; set; }

    public virtual VaccinationFacility Facility { get; set; }
}