// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class FacilityVaccine
{
    public int FacilityVaccineId { get; set; }

    public int FacilityId { get; set; }

    public int VaccineId { get; set; }

    public decimal Price { get; set; }

    public int AvailableQuantity { get; set; }

    public int BatchNumber { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public DateOnly ImportDate { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual VaccinationFacility Facility { get; set; }

    public virtual ICollection<PackageVaccine> PackageVaccines { get; set; } = new List<PackageVaccine>();

    public virtual Vaccine Vaccine { get; set; }
}