// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class FacilityMembershipSubscription
{
    public int SubscriptionId { get; set; }

    public int FacilityId { get; set; }

    public int FacilityMembershipId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual VaccinationFacility Facility { get; set; }

    public virtual FacilityMembership FacilityMembership { get; set; }
}