// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class FacilityVaccine
{
    public int FacilityVaccineId { get; set; }

    public int FacilityId { get; set; }

    public int VaccineId { get; set; }

    public decimal Price { get; set; }

    public int AvailableQuantity { get; set; }

    public bool Status { get; set; }
}