// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Faq
{
    public int FaqId { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public string Category { get; set; }

    public bool Status { get; set; }
}