// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class GrowthPrediction
{
    public int PredictionId { get; set; }

    public int ChildId { get; set; }

    public DateTime PredictionDate { get; set; }

    public decimal PredictedHeight { get; set; }

    public decimal PredictedWeight { get; set; }

    public decimal PredictedBmi { get; set; }

    public decimal ConfidenceLevel { get; set; }
}