// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Entities;

public partial class HealthChildTrackerContext : DbContext
{
    public HealthChildTrackerContext(DbContextOptions<HealthChildTrackerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<Child> Children { get; set; }

    public virtual DbSet<ChildDiary> ChildDiaries { get; set; }

    public virtual DbSet<ChildVaccination> ChildVaccinations { get; set; }

    public virtual DbSet<FacilityVaccine> FacilityVaccines { get; set; }

    public virtual DbSet<Faq> Faqs { get; set; }

    public virtual DbSet<GrowthPrediction> GrowthPredictions { get; set; }

    public virtual DbSet<GrowthRecord> GrowthRecords { get; set; }

    public virtual DbSet<GrowthStandard> GrowthStandards { get; set; }

    public virtual DbSet<Membership> Memberships { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserMembership> UserMemberships { get; set; }

    public virtual DbSet<VaccinationAppointment> VaccinationAppointments { get; set; }

    public virtual DbSet<VaccinationFacility> VaccinationFacilities { get; set; }

    public virtual DbSet<Vaccine> Vaccines { get; set; }

    public virtual DbSet<VaccineSchedule> VaccineSchedules { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(entity =>
        {
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Child>(entity =>
        {
            entity.Property(e => e.AllergiesNotes).IsRequired();
            entity.Property(e => e.BirthDate).HasColumnType("datetime");
            entity.Property(e => e.BloodType)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.MedicalHistory).IsRequired();
            entity.Property(e => e.ParentName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ParentNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<ChildDiary>(entity =>
        {
            entity.HasKey(e => e.DiaryId);

            entity.ToTable("ChildDiary");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Note).IsRequired();
            entity.Property(e => e.SleepHours).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<ChildVaccination>(entity =>
        {
            entity.HasKey(e => e.VaccinationId);

            entity.Property(e => e.NextVaccinationDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.VaccinationDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<FacilityVaccine>(entity =>
        {
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Faq>(entity =>
        {
            entity.ToTable("FAQs");

            entity.Property(e => e.Answer).IsRequired();
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Question).IsRequired();
        });

        modelBuilder.Entity<GrowthPrediction>(entity =>
        {
            entity.HasKey(e => e.PredictionId);

            entity.Property(e => e.ConfidenceLevel).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.PredictedBmi)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("PredictedBMI");
            entity.Property(e => e.PredictedHeight).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.PredictedWeight).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.PredictionDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<GrowthRecord>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.Property(e => e.Bmi)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("BMI");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.HeadCircumference).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.Height).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.Note).IsRequired();
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Weight).HasColumnType("decimal(8, 2)");
        });

        modelBuilder.Entity<GrowthStandard>(entity =>
        {
            entity.HasKey(e => e.StandardId);

            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Measurement)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Median).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.Sd1neg)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("SD1neg");
            entity.Property(e => e.Sd1pos)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("SD1pos");
            entity.Property(e => e.Sd2neg)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("SD2neg");
            entity.Property(e => e.Sd2pos)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("SD2pos");
            entity.Property(e => e.Sd3neg)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("SD3neg");
            entity.Property(e => e.Sd3pos)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("SD3pos");
        });

        modelBuilder.Entity<Membership>(entity =>
        {
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(8, 2)");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.Property(e => e.Comment).IsRequired();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.Property(e => e.Amount).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TransactionCode)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<UserMembership>(entity =>
        {
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.LastRenewalDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<VaccinationAppointment>(entity =>
        {
            entity.HasKey(e => e.AppointmentId);

            entity.Property(e => e.AppointmentDate).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<VaccinationFacility>(entity =>
        {
            entity.HasKey(e => e.FacilityId);

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.LicenseNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Vaccine>(entity =>
        {
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Manufacturer)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<VaccineSchedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId);

            entity.Property(e => e.Description).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}