// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Nationality
{
    public int NationId { get; set; }

    public string NationName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Child> Children { get; set; } = new List<Child>();

    public virtual ICollection<GrowthStandard> GrowthStandards { get; set; } = new List<GrowthStandard>();
}