// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class NotificationDeliveryStatus
{
    public int NotificationDeliveryStatusId { get; set; }

    public int NotificationHistoryId { get; set; }

    public int DeviceTokenId { get; set; }

    public string Status { get; set; }

    public string FirebaseMessageId { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime SentAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public DateTime? ClickedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual DeviceToken DeviceToken { get; set; }

    public virtual NotificationHistory NotificationHistory { get; set; }
}