// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class NotificationHistory
{
    public int NotificationHistoryId { get; set; }

    public int AccountId { get; set; }

    public string NotificationType { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public string Data { get; set; }

    public DateTime SentAt { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public int? ChildId { get; set; }

    public int? VaccineId { get; set; }

    public int? AppointmentId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual VaccinationAppointment Appointment { get; set; }

    public virtual Child Child { get; set; }

    public virtual ICollection<NotificationDeliveryStatus> NotificationDeliveryStatuses { get; set; } = new List<NotificationDeliveryStatus>();

    public virtual Vaccine Vaccine { get; set; }
}