// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int OrderId { get; set; }

    public int FacilityVaccineId { get; set; }

    public int DiseaseId { get; set; }

    public int RemainingQuantity { get; set; }

    public decimal Price { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Disease Disease { get; set; }

    public virtual FacilityVaccine FacilityVaccine { get; set; }

    public virtual Vaccine FacilityVaccineNavigation { get; set; }

    public virtual Order Order { get; set; }
}