// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class PackageVaccine
{
    public int PackageVaccineId { get; set; }

    public int PackageId { get; set; }

    public int FacilityVaccineId { get; set; }

    public int DiseaseId { get; set; }

    public int Quantity { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual FacilityVaccine FacilityVaccine { get; set; }

    public virtual VaccinePackage Package { get; set; }
}