// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class SurveyQuestion
{
    public int QuestionId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public int SurveyId { get; set; }

    public bool IsRequired { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AppointmentSurvey> AppointmentSurveys { get; set; } = new List<AppointmentSurvey>();

    public virtual HealthSurvey Survey { get; set; }

    public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; } = new List<SurveyAnswer>();
}