// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int TransactionType { get; set; }

    public int DocNo { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionCode { get; set; }

    public string Description { get; set; }

    public DateOnly CreatedAt { get; set; }
}