// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class UserMembership
{
    public int UserMembershipId { get; set; }

    public int AccountId { get; set; }

    public int MembershipId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool Status { get; set; }

    public DateOnly LastRenewalDate { get; set; }

    public virtual Account Account { get; set; }

    public virtual Membership Membership { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}