// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccineTemplate
{
    public int Id { get; set; }

    public int DiseaseId { get; set; }

    public TimeOnly PeriodFrom { get; set; }

    public TimeOnly PeriodTo { get; set; }

    public string Description { get; set; }

    public bool IsRequired { get; set; }

    public string Priority { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Disease Disease { get; set; }
}