// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccinationAppointment
{
    public int AppointmentId { get; set; }

    public int ChildId { get; set; }

    public int ScheduleId { get; set; }

    public int? OrderId { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AppointmentSurvey> AppointmentSurveys { get; set; } = new List<AppointmentSurvey>();

    public virtual Child Child { get; set; }

    public virtual ICollection<ChildVaccineProfile> ChildVaccineProfiles { get; set; } = new List<ChildVaccineProfile>();

    public virtual ICollection<NotificationHistory> NotificationHistories { get; set; } = new List<NotificationHistory>();

    public virtual Order Order { get; set; }

    public virtual AppointmentSchedule Schedule { get; set; }

    public virtual ICollection<VaccinationAppointmentDetail> VaccinationAppointmentDetails { get; set; } = new List<VaccinationAppointmentDetail>();
}