// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccinationAppointment
{
    public int AppointmentId { get; set; }

    public int ChildId { get; set; }

    public int FacilityId { get; set; }

    public int VaccineId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}