// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccineDisease
{
    public int VaccineDiseaseId { get; set; }

    public int DiseaseId { get; set; }

    public int VaccineId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Disease Disease { get; set; }

    public virtual Vaccine Vaccine { get; set; }
}