// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccinationAppointmentDetail
{
    public int DetailId { get; set; }

    public int AppointmentId { get; set; }

    public int VaccineId { get; set; }

    public DateOnly VaccinationDate { get; set; }

    public string DoseNumber { get; set; }

    public decimal? FacilityVaccinePrice { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual VaccinationAppointment Appointment { get; set; }

    public virtual Vaccine Vaccine { get; set; }
}