// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccinationFacility
{
    public int FacilityId { get; set; }

    public string FacilityName { get; set; }

    public int LicenseNumber { get; set; }

    public string Address { get; set; }

    public int Phone { get; set; }

    public string Email { get; set; }

    public string Description { get; set; }

    public long Status { get; set; }

    public long CreatedAt { get; set; }

    public long UpdatedAt { get; set; }

    public virtual ICollection<AppointmentSchedule> AppointmentSchedules { get; set; } = new List<AppointmentSchedule>();

    public virtual ICollection<FacilityMembershipSubscription> FacilityMembershipSubscriptions { get; set; } = new List<FacilityMembershipSubscription>();

    public virtual ICollection<FacilityRating> FacilityRatings { get; set; } = new List<FacilityRating>();

    public virtual ICollection<FacilityStaff> FacilityStaffs { get; set; } = new List<FacilityStaff>();

    public virtual ICollection<FacilityVaccine> FacilityVaccines { get; set; } = new List<FacilityVaccine>();

    public virtual ICollection<ScheduleSlot> ScheduleSlots { get; set; } = new List<ScheduleSlot>();

    public virtual ICollection<VaccinePackage> VaccinePackages { get; set; } = new List<VaccinePackage>();
}