// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class VaccinationFacilityPaymentAccount
{
    public int Id { get; set; }

    public int FacilityId { get; set; }

    public string BankName { get; set; }

    public string AccountNumber { get; set; }

    public string AccountHolder { get; set; }

    public string QrcodeImageUrl { get; set; }

    public string IsActive { get; set; }

    public DateOnly CreatedAt { get; set; }

    public DateOnly UpdatedAt { get; set; }

    public virtual VaccinationFacility Facility { get; set; }
}