<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Member\" />
    <Folder Include="DTOs\Membership\" />
    <Folder Include="DTOs\FacilitySubcription\" />
    <Folder Include="DTOs\Appointment\" />
    <Folder Include="DTOs\FacilitySchedule\" />
    <Folder Include="DTOs\Blog\" />
    <Folder Include="DTOs\Transaction\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="payOS" Version="1.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repositories\Repositories.csproj" />
  </ItemGroup>

</Project>
